spring:
  application:
    name: zuul
  rabbitmq: 
    host: 192.168.186.135
    port: 5672
    username: admin
    password: admin
        
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/rureka, http://eureka2:2002/eureka      
zuul:
  retryable: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  