spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/rureka, http://eureka2:2002/eureka      
zuul:
  retryable: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  